/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControllerClienteEndereco;
import Controller.ControllerClientes;
import Controller.ControllerEnderecos;
import Model.ModelClienteEndereco;
import Model.ModelClientes;
import Model.ModelEnderecos;
import com.sun.media.jfxmedia.events.NewFrameEvent;
import conexoes.ConexaoMySql;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Matheus
 */
public class Clientes extends javax.swing.JFrame {

    ModelClientes modelCliente = new ModelClientes();
    ModelEnderecos modelEnderecos = new ModelEnderecos();
    ModelClienteEndereco modelEndCli = new ModelClienteEndereco();
    ControllerClientes controllerClientes = new ControllerClientes();
    ControllerEnderecos controllerEnderecos = new ControllerEnderecos();
    ControllerClienteEndereco controllerEndCli = new ControllerClienteEndereco();
       
    public static String documento = "";

    /**
     * Creates new form Clientes
     */
    public Clientes() {

        initComponents();
        jftfDocumento.setEnabled(false);
        jftfTelefone.setEnabled(false);
        setLocationRelativeTo(null);
        jtfCodCliente.setEnabled(false);
        jtfCodEndereco.setEnabled(false);
        

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodEndereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jftfCep = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfComplemento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfBairro = new javax.swing.JTextField();
        jtfRua = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jtfCodCliente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jradioCpf = new javax.swing.JRadioButton();
        jradioOutros = new javax.swing.JRadioButton();
        jrCelular = new javax.swing.JRadioButton();
        jradioTelefone = new javax.swing.JRadioButton();
        jftfDocumento = new javax.swing.JFormattedTextField();
        jftfTelefone = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-gestão-de-cliente-50.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 22)); // NOI18N
        jLabel10.setText("ELETRÔNICA ALVORADA");

        jLabel12.setText("                             CADASTRO DE CLIENTES");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-gestão-de-cliente-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(121, 121, 121)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addContainerGap())
        );

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("CÓD END");

        jLabel3.setText("CEP");

        try {
            jftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jftfCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftfCepFocusLost(evt);
            }
        });

        jLabel4.setText("RUA");

        jLabel7.setText("CIDADE");

        jLabel8.setText("NUMERO");

        jLabel9.setText("COMPLE");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-endereço-30.png"))); // NOI18N
        jButton1.setText("CADASTRAR ENDEREÇO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("BAIRRO");

        jtfRua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfRuaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCodEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtfCodEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jtfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel11.setText("COD CLI");

        jLabel13.setText("NOME");

        jLabel14.setText("DOCUMENTO");

        jLabel15.setText("CONTATO");

        buttonGroup1.add(jradioCpf);
        jradioCpf.setText("CPF");
        jradioCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioCpfActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradioOutros);
        jradioOutros.setText("OUTRO");
        jradioOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioOutrosActionPerformed(evt);
            }
        });

        buttonGroup2.add(jrCelular);
        jrCelular.setText("CELULAR");
        jrCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrCelularActionPerformed(evt);
            }
        });

        buttonGroup2.add(jradioTelefone);
        jradioTelefone.setText("TELEFONE");
        jradioTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfNome))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jradioCpf)
                                .addGap(135, 135, 135)
                                .addComponent(jradioOutros))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftfDocumento)))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jftfTelefone))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jrCelular)
                                .addGap(43, 43, 43)
                                .addComponent(jradioTelefone)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jftfDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jradioCpf)
                    .addComponent(jradioOutros)
                    .addComponent(jrCelular)
                    .addComponent(jradioTelefone))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-visualizar-arquivo-30.png"))); // NOI18N
        jButton2.setText("BUSCAR");
        jButton2.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-edit-text-file-30.png"))); // NOI18N
        jButton3.setText("CADASTRAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-atualizar-arquivo-30.png"))); // NOI18N
        jButton4.setText("ATUALIZAR");
        jButton4.setPreferredSize(new java.awt.Dimension(130, 36));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-avançar-30.png"))); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-voltar-30.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton3)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked

        RelatorioDeConsertos menu = new RelatorioDeConsertos();
        this.dispose();
        menu.setVisible(true);

    }//GEN-LAST:event_jLabel18MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try {

            modelCliente.setCli_Nome(this.jtfNome.getText());
            modelCliente.setCli_Documento(this.jftfDocumento.getText());
            modelCliente.setCli_Telefone(this.jftfTelefone.getText());
            modelCliente.setCli_CodEndereco(Integer.parseInt(this.jtfCodEndereco.getText()));
            modelCliente.setCli_Numero(Integer.parseInt(this.jtfNumero.getText()));
            modelCliente.setCli_Complemento(this.jtfComplemento.getText());

            if (controllerClientes.salvarClienteController(modelCliente) > 0) {

                JOptionPane.showMessageDialog(this, "Cliente Cadastrado Com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                limparCampos();

            } else {

                JOptionPane.showMessageDialog(this, "Erro Ao Cadastrar Cliente!", "ERRO", JOptionPane.ERROR_MESSAGE);

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Certifique Que Preencheu Todos Os Campos!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        ConexaoMySql conexao = new ConexaoMySql();

        String nome = jtfNome.getText();

        try {

            conexao.conectar();
            conexao.executarSQL("select c.cli_codcliente,c.cli_nome,c.cli_documento,c.cli_telefone,e.end_codendereco,e.end_cep,e.end_rua,c.cli_numeroEndereco,c.cli_complementoEndereco,e.end_bairro,e.end_cidade "
                    + "from clientes as c inner join enderecos as e on (c.cli_codendereco = e.end_codendereco) "
                    + "where c.cli_nome like '" + nome + "';");

            if (conexao.getResultSet().next()) {

                desbloquearCampos();

                jtfCodCliente.setText(conexao.getResultSet().getString("cli_codcliente"));
                jtfNome.setText(conexao.getResultSet().getString("cli_nome"));
                jftfDocumento.setText(conexao.getResultSet().getString("cli_documento"));
                jftfTelefone.setText(conexao.getResultSet().getString("cli_telefone"));
                jtfCodEndereco.setText(conexao.getResultSet().getString("end_codendereco"));
                jftfCep.setText(conexao.getResultSet().getString("end_cep"));
                jtfRua.setText(conexao.getResultSet().getString("end_rua"));
                jtfNumero.setText(conexao.getResultSet().getString("cli_numeroEndereco"));
                jtfComplemento.setText(conexao.getResultSet().getString("cli_complementoEndereco"));
                jtfBairro.setText(conexao.getResultSet().getString("end_bairro"));
                jtfCidade.setText(conexao.getResultSet().getString("end_cidade"));

            } else {

                JOptionPane.showMessageDialog(this, "Cliente Não Encontrado", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

            }

        } catch (Exception e) {

            e.printStackTrace();

        } finally {

            conexao.fecharConexao();

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {

            modelCliente.setCli_CodCliente(Integer.parseInt(this.jtfCodCliente.getText()));
            modelCliente.setCli_Nome(this.jtfNome.getText());
            modelCliente.setCli_Documento(this.jftfDocumento.getText());
            modelCliente.setCli_Telefone(this.jftfTelefone.getText());
            modelCliente.setCli_CodEndereco(Integer.parseInt(this.jtfCodEndereco.getText()));
            modelCliente.setCli_Complemento(this.jtfComplemento.getText());
            modelCliente.setCli_Numero(Integer.parseInt(this.jtfNumero.getText()));

            if (controllerClientes.alterarClienteController(modelCliente)) {

                JOptionPane.showMessageDialog(this, "Cliente Alterado Com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                limparCampos();
                bloquearCampos();

            } else {

                JOptionPane.showMessageDialog(this, "Erro Ao Alterado Cliente!", "ERRO", JOptionPane.ERROR_MESSAGE);

            }

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(this, "Certifique Que Preencheu Todos Os Campos!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked

        NewJFrame apa = new NewJFrame();
        documento = jftfDocumento.getText();
        this.dispose();
        apa.setVisible(true);
        
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jradioCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioCpfActionPerformed

        try {

            if (jftfDocumento.getText().equals("")) {

                jftfDocumento.setEnabled(true);
                jftfDocumento.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("###.###.###-##")));

            } else {

                JOptionPane.showMessageDialog(this, "Não É Possivel Mudar O Formato do Campo!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

            }

        } catch (ParseException ex) {

            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_jradioCpfActionPerformed

    private void jradioOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioOutrosActionPerformed

        if (jftfDocumento.getText().equals("")) {

            jftfDocumento.setEnabled(true);

        } else {

            JOptionPane.showMessageDialog(this, "Não É Possivel Mudar O Formato do Campo!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_jradioOutrosActionPerformed

    private void jrCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrCelularActionPerformed

        try {

            if (jftfTelefone.getText().equals("")) {

                jftfTelefone.setEnabled(true);
                jftfTelefone.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("(##) #####-####")));

            } else {

                JOptionPane.showMessageDialog(this, "Não É Possivel Mudar O Formato do Campo!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

            }

        } catch (ParseException ex) {

            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_jrCelularActionPerformed

    private void jradioTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioTelefoneActionPerformed

        try {

            if (jftfTelefone.getText().equals("")) {

                jftfTelefone.setEnabled(true);
                jftfTelefone.setFormatterFactory(new DefaultFormatterFactory(new MaskFormatter("(##) ####-####")));

            } else {

                JOptionPane.showMessageDialog(this, "Não É Possivel Mudar O Formato do Campo!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

            }

        } catch (ParseException ex) {

            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_jradioTelefoneActionPerformed

    private void jftfCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftfCepFocusLost

        if (!jftfCep.getText().equals("     -   ")) {

            modelEnderecos = controllerEnderecos.retornaCodEnderecoController(jftfCep.getText());

            try {

                if (!modelEnderecos.getEnd_Cep().equals("")) {

                    buscarRua();

                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(rootPane, "Endereço Não Encontrado Favor Cadastrar");

            }

        }

    }//GEN-LAST:event_jftfCepFocusLost

    private void jtfRuaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfRuaFocusLost

        if (!jtfRua.getText().equals("")) {

            modelEnderecos = controllerEnderecos.retornaCodEnderecoController(jtfRua.getText());

            try {

                if (!modelEnderecos.getEnd_Cep().equals("")) {

                    buscarRua();

                }

            } catch (Exception e) {

                JOptionPane.showMessageDialog(rootPane, "Endereço Não Encontrado Favor Cadastrar");

            }
        }

    }//GEN-LAST:event_jtfRuaFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Enderecos end = new Enderecos();
        end.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JFormattedTextField jftfCep;
    private javax.swing.JFormattedTextField jftfDocumento;
    private javax.swing.JFormattedTextField jftfTelefone;
    private javax.swing.JRadioButton jrCelular;
    private javax.swing.JRadioButton jradioCpf;
    private javax.swing.JRadioButton jradioOutros;
    private javax.swing.JRadioButton jradioTelefone;
    private javax.swing.JTextField jtfBairro;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfCodCliente;
    private javax.swing.JTextField jtfCodEndereco;
    private javax.swing.JTextField jtfComplemento;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfRua;
    // End of variables declaration//GEN-END:variables

    public void buscarRua() {

        jtfCodEndereco.setText(String.valueOf(modelEnderecos.getEnd_CodEndereco()));
        jftfCep.setText(modelEnderecos.getEnd_Cep());
        jtfRua.setText(modelEnderecos.getEnd_Rua());
        jtfNumero.setText(String.valueOf(modelEnderecos.getEnd_Numero()));
        jtfComplemento.setText(modelEnderecos.getEnd_Complemento());
        jtfBairro.setText(modelEnderecos.getEnd_Bairro());
        jtfCidade.setText(modelEnderecos.getEnd_Cidade());

    }

    public void limparCampos() {

        jtfCodCliente.setText(" ");
        jtfNome.setText(" ");
        jftfDocumento.setText("");
        jftfTelefone.setText("");
        jtfCodEndereco.setText(" ");
        jftfCep.setText("");
        jtfRua.setText(" ");
        jtfNumero.setText(" ");
        jtfComplemento.setText(" ");
        jtfBairro.setText(" ");
        jtfCidade.setText(" ");

    }

    public void bloquearCampos() {

        jftfDocumento.setEnabled(false);
        jftfTelefone.setEnabled(false);

    }

    public void desbloquearCampos() {

        jftfDocumento.setEnabled(true);
        jftfTelefone.setEnabled(true);

    }
}
