/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controleleds;

import ComunicacaoArduino.ArduinoSerial;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Matheus
 */
public class ControleLedsArduino extends javax.swing.JFrame {

    /**
     * Creates new form ControleLedsArduino
     */
    String comando = "00 00 000 00 000.000.000;", valorCustomizacao = "00", valorEfeito = "00", valorBrilho = "000", valorTempo = "00", valorVermelho = "000", valorVerde = "000", valorAzul = "000";
    int brilho = 0, tempo = 0, vermelho = 0, verde = 0, azul = 0;

    ArduinoSerial arduino = new ArduinoSerial("COM5");

    public ControleLedsArduino() {

        initComponents();
        jTextFieldCor.setBackground(Color.black);
        arduino.initialize();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderBrilho = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerBrilho = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCustomizacao = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxEfeito = new javax.swing.JComboBox<>();
        jSpinnerTempo = new javax.swing.JSpinner();
        jSliderTempo = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSliderVermelho = new javax.swing.JSlider();
        jSpinnerVermelho = new javax.swing.JSpinner();
        jSliderVerde = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerVerde = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerAzul = new javax.swing.JSpinner();
        jSliderAzul = new javax.swing.JSlider();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldComando = new javax.swing.JTextField();
        jTextFieldCor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonConcatenar = new javax.swing.JButton();
        jButtonSubstituir = new javax.swing.JButton();
        jButtonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jSliderBrilho.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jSliderBrilho.setMajorTickSpacing(51);
        jSliderBrilho.setMaximum(255);
        jSliderBrilho.setPaintLabels(true);
        jSliderBrilho.setPaintTicks(true);
        jSliderBrilho.setValue(0);
        jSliderBrilho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSliderBrilho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderBrilhoStateChanged(evt);
            }
        });

        jLabel1.setText("BRILHO");

        jSpinnerBrilho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerBrilhoStateChanged(evt);
            }
        });

        jLabel8.setText("CUSTOMIZAÇÃO");

        jComboBoxCustomizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE", "UMA COR", "DUAS CORES", "TRÊS CORES", "CINCO CORES", "ALEATÓRIO" }));
        jComboBoxCustomizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCustomizacaoActionPerformed(evt);
            }
        });

        jLabel9.setText("EFEITO");

        jComboBoxEfeito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE" }));
        jComboBoxEfeito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxEfeitoFocusLost(evt);
            }
        });

        jSpinnerTempo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerTempoStateChanged(evt);
            }
        });

        jSliderTempo.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jSliderTempo.setMajorTickSpacing(1);
        jSliderTempo.setMaximum(10);
        jSliderTempo.setMinorTickSpacing(1);
        jSliderTempo.setPaintLabels(true);
        jSliderTempo.setPaintTicks(true);
        jSliderTempo.setValue(0);
        jSliderTempo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSliderTempo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderTempoStateChanged(evt);
            }
        });

        jLabel10.setText("TEMPO");

        jLabel11.setText("VERMELHO");

        jSliderVermelho.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jSliderVermelho.setMajorTickSpacing(51);
        jSliderVermelho.setMaximum(255);
        jSliderVermelho.setPaintLabels(true);
        jSliderVermelho.setPaintTicks(true);
        jSliderVermelho.setValue(0);
        jSliderVermelho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSliderVermelho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVermelhoStateChanged(evt);
            }
        });

        jSpinnerVermelho.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerVermelhoStateChanged(evt);
            }
        });

        jSliderVerde.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jSliderVerde.setMajorTickSpacing(51);
        jSliderVerde.setMaximum(255);
        jSliderVerde.setPaintLabels(true);
        jSliderVerde.setPaintTicks(true);
        jSliderVerde.setValue(0);
        jSliderVerde.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSliderVerde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVerdeStateChanged(evt);
            }
        });

        jLabel12.setText("VERDE");

        jSpinnerVerde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerVerdeStateChanged(evt);
            }
        });

        jLabel13.setText("AZUL");

        jSpinnerAzul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAzulStateChanged(evt);
            }
        });

        jSliderAzul.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jSliderAzul.setMajorTickSpacing(51);
        jSliderAzul.setMaximum(255);
        jSliderAzul.setPaintLabels(true);
        jSliderAzul.setPaintTicks(true);
        jSliderAzul.setValue(0);
        jSliderAzul.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSliderAzul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAzulStateChanged(evt);
            }
        });

        jLabel14.setText("COMANDO");

        jLabel2.setText("COR");

        jButtonConcatenar.setText("CONCATENAR");
        jButtonConcatenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcatenarActionPerformed(evt);
            }
        });

        jButtonSubstituir.setText("SUBSTITUIR");
        jButtonSubstituir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubstituirActionPerformed(evt);
            }
        });

        jButtonEnviar.setText("ENVIAR");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxCustomizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jComboBoxEfeito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSliderBrilho, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerBrilho, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSliderTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSliderVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSliderVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSliderAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCor))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(238, 238, 238)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldComando, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConcatenar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSubstituir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEfeito, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCustomizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jSliderBrilho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinnerBrilho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jSliderTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSpinnerTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jSliderVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSpinnerVermelho, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jSliderVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSpinnerVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jSliderAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSpinnerAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCor, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonConcatenar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jTextFieldComando))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSubstituir, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButtonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCustomizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCustomizacaoActionPerformed

        String Customizacao = (String) jComboBoxCustomizacao.getSelectedItem();

        if (Customizacao.equals("UMA COR")) {

            jComboBoxEfeito.removeAllItems();
            jComboBoxEfeito.addItem("SELECIONE");
            jComboBoxEfeito.addItem("SOLIDO");
            jComboBoxEfeito.addItem("PISCA COR");
            jComboBoxEfeito.addItem("RESPIRAÇÃO");
            jComboBoxEfeito.addItem("THEATERCHASE");
            jComboBoxEfeito.addItem("CIRCULA COR");
            jComboBoxEfeito.addItem("CHUVA DE METEOROS");

            valorCustomizacao = "01";

        } else if (Customizacao.equals("DUAS CORES")) {

            jComboBoxEfeito.removeAllItems();
            jComboBoxEfeito.addItem("SELECIONE");
            jComboBoxEfeito.addItem("SOLIDO");
            jComboBoxEfeito.addItem("PISCA COR");
            jComboBoxEfeito.addItem("RESPIRAÇÃO");
            jComboBoxEfeito.addItem("RESPIRAÇÃO JUNTA");
            jComboBoxEfeito.addItem("MUDAR CORES");
            jComboBoxEfeito.addItem("THEATERCHASE");

            valorCustomizacao = "02";

        } else if (Customizacao.equals("TRÊS CORES")) {

            jComboBoxEfeito.removeAllItems();
            jComboBoxEfeito.addItem("SELECIONE");
            jComboBoxEfeito.addItem("SOLIDO");
            jComboBoxEfeito.addItem("PISCA COR");
            jComboBoxEfeito.addItem("RESPIRAÇÃO");
            jComboBoxEfeito.addItem("RESPIRAÇÃO JUNTA");
            jComboBoxEfeito.addItem("MUDAR CORES");

            valorCustomizacao = "03";

        } else if (Customizacao.equals("CINCO CORES")) {

            jComboBoxEfeito.removeAllItems();
            jComboBoxEfeito.addItem("SELECIONE");
            jComboBoxEfeito.addItem("RESPIRAÇÃO");
            jComboBoxEfeito.addItem("MUDAR CORES");

            valorCustomizacao = "05";

        } else if (Customizacao.equals("ALEATÓRIO")) {

            jComboBoxEfeito.removeAllItems();
            jComboBoxEfeito.addItem("SELECIONE");
            jComboBoxEfeito.addItem("VARIAS CORES");
            jComboBoxEfeito.addItem("RESPIRAÇÃO");
            jComboBoxEfeito.addItem("MUDAR CORES");

            valorCustomizacao = "06";

        }

    }//GEN-LAST:event_jComboBoxCustomizacaoActionPerformed

    private void jComboBoxEfeitoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxEfeitoFocusLost

        String Efeito = (String) jComboBoxEfeito.getSelectedItem();

        if (Efeito.equals("SOLIDO") || Efeito.equals("VARIAS CORES")) {

            valorEfeito = "01";

        } else if (Efeito.equals("PISCA COR")) {

            valorEfeito = "02";

        } else if (Efeito.equals("RESPIRAÇÃO")) {

            valorEfeito = "03";

        } else if (Efeito.equals("RESPIRAÇÃO JUNTO")) {

            valorEfeito = "04";

        } else if (Efeito.equals("MUDAR COR")) {

            valorEfeito = "05";

        } else if (Efeito.equals("THEATERCHASE")) {

            valorEfeito = "07";

        } else if (Efeito.equals("CIRCULA COR")) {

            valorEfeito = "08";

        } else if (Efeito.equals("CHUVA DE METEOROS")) {

            valorEfeito = "09";

        }

    }//GEN-LAST:event_jComboBoxEfeitoFocusLost

    private void jSliderBrilhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderBrilhoStateChanged

        jSpinnerBrilho.setValue((int) jSliderBrilho.getValue());

    }//GEN-LAST:event_jSliderBrilhoStateChanged

    private void jSpinnerBrilhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerBrilhoStateChanged

        brilho = (int) jSpinnerBrilho.getValue();
        jSliderBrilho.setValue(brilho);

        if (brilho < 0) {

            JOptionPane.showMessageDialog(rootPane, "Valor Minimo");
            jSpinnerBrilho.setValue(0);

        } else if (brilho < 9) {

            valorBrilho = "00" + brilho;

        } else if (brilho < 99) {

            valorBrilho = "0" + brilho;

        } else if (brilho <= 255) {

            valorBrilho = "" + brilho;

        } else if (brilho > 255) {

            JOptionPane.showMessageDialog(rootPane, "Valor Maximo");
            jSpinnerBrilho.setValue(255);

        }

    }//GEN-LAST:event_jSpinnerBrilhoStateChanged

    private void jSliderTempoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderTempoStateChanged

        jSpinnerTempo.setValue((int) jSliderTempo.getValue());

    }//GEN-LAST:event_jSliderTempoStateChanged

    private void jSpinnerTempoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerTempoStateChanged

        tempo = (int) jSpinnerTempo.getValue();
        jSliderTempo.setValue(tempo);

        if (tempo < 0) {

            JOptionPane.showMessageDialog(rootPane, "Valor Minimo");
            jSpinnerTempo.setValue(0);

        } else if (tempo < 9) {

            valorTempo = "0" + tempo;

        } else if (tempo == 10) {

            valorTempo = "" + tempo;

        } else if (tempo > 10) {

            JOptionPane.showMessageDialog(rootPane, "Valor Maximo");
            jSpinnerTempo.setValue(10);

        }

    }//GEN-LAST:event_jSpinnerTempoStateChanged

    private void jSliderVermelhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVermelhoStateChanged

        jSpinnerVermelho.setValue((int) jSliderVermelho.getValue());

    }//GEN-LAST:event_jSliderVermelhoStateChanged

    private void jSpinnerVermelhoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerVermelhoStateChanged

        vermelho = (int) jSpinnerVermelho.getValue();
        jSliderVermelho.setValue(vermelho);

        if (vermelho < 0) {

            JOptionPane.showMessageDialog(rootPane, "Valor Minimo");
            jSpinnerVermelho.setValue(0);

        } else if (vermelho < 9) {

            valorVermelho = "00" + vermelho;

        } else if (vermelho < 99) {

            valorVermelho = "0" + vermelho;

        } else if (vermelho <= 255) {

            valorVermelho = "" + vermelho;

        } else if (vermelho > 255) {

            JOptionPane.showMessageDialog(rootPane, "Valor Maximo");
            jSpinnerVermelho.setValue(255);

        }

        jTextFieldCor.setBackground(new Color(vermelho, verde, azul));

    }//GEN-LAST:event_jSpinnerVermelhoStateChanged

    private void jSliderVerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVerdeStateChanged

        jSpinnerVerde.setValue((int) jSliderVerde.getValue());

    }//GEN-LAST:event_jSliderVerdeStateChanged

    private void jSpinnerVerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerVerdeStateChanged

        verde = (int) jSpinnerVerde.getValue();
        jSliderVerde.setValue(verde);

        if (verde < 0) {

            JOptionPane.showMessageDialog(rootPane, "Valor Minimo");
            jSpinnerVerde.setValue(0);

        } else if (verde < 9) {

            valorVerde = "00" + verde;

        } else if (verde < 99) {

            valorVerde = "0" + verde;

        } else if (verde <= 255) {

            valorVerde = "" + verde;

        } else if (verde > 255) {

            JOptionPane.showMessageDialog(rootPane, "Valor Maximo");
            jSpinnerVerde.setValue(255);

        }

        jTextFieldCor.setBackground(new Color(vermelho, verde, azul));

    }//GEN-LAST:event_jSpinnerVerdeStateChanged

    private void jSliderAzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAzulStateChanged

        jSpinnerAzul.setValue((int) jSliderAzul.getValue());

    }//GEN-LAST:event_jSliderAzulStateChanged

    private void jSpinnerAzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAzulStateChanged

        azul = (int) jSpinnerAzul.getValue();
        jSliderAzul.setValue(azul);

        if (azul < 0) {

            JOptionPane.showMessageDialog(rootPane, "Valor Minimo");
            jSpinnerAzul.setValue(0);

        } else if (azul < 9) {

            valorAzul = "00" + azul;

        } else if (azul < 99) {

            valorAzul = "0" + azul;

        } else if (azul <= 255) {

            valorAzul = "" + azul;

        } else if (azul > 255) {

            JOptionPane.showMessageDialog(rootPane, "Valor Maximo");
            jSpinnerAzul.setValue(255);

        }

        jTextFieldCor.setBackground(new Color(vermelho, verde, azul));

    }//GEN-LAST:event_jSpinnerAzulStateChanged

    private void jButtonConcatenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcatenarActionPerformed

        String textoComando = jTextFieldComando.getText();
        int tamanhoComando = textoComando.length();

        comando = valorCustomizacao + " " + valorEfeito + " " + valorBrilho + " " + valorTempo + " " + valorVermelho + "." + valorVerde + "." + valorAzul;

        if (textoComando.contains(valorVermelho + "." + valorVerde + "." + valorAzul)) {

            JOptionPane.showMessageDialog(rootPane, "Valor Igual");

        } else {

            if (tamanhoComando == 0) {

                jTextFieldComando.setText(comando);

            } else if (tamanhoComando >= 24 && tamanhoComando <= 72) {

                jTextFieldComando.setText(textoComando + " " + valorVermelho + "." + valorVerde + "." + valorAzul);

            }
        }

    }//GEN-LAST:event_jButtonConcatenarActionPerformed

    private void jButtonSubstituirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubstituirActionPerformed

        try {

            String comandoTexto = jTextFieldComando.getText();
            int opcao = Integer.parseInt(JOptionPane.showInputDialog("Digite Valor: "));

            if (comandoTexto.contains(valorCustomizacao + " " + valorEfeito + " " + valorBrilho + " " + valorTempo) && comandoTexto.contains(valorVermelho + "." + valorVerde + "." + valorAzul)) {

                JOptionPane.showMessageDialog(rootPane, "Comando Igual");

            } else {

                if (opcao == 0) {

                    comando = comando.replace(comando.substring(opcao, opcao + 12), valorCustomizacao + " " + valorEfeito + " " + valorBrilho + " " + valorTempo);
                    jTextFieldComando.setText(comando);

                } else {

                    comando = comandoTexto.replace(comandoTexto.substring(opcao, opcao + 12), "/");
                    comando = comando.replace("/", " " + valorVermelho + "." + valorVerde + "." + valorAzul);

                    jTextFieldComando.setText(comando);

                }
            }

        } catch (NumberFormatException | StringIndexOutOfBoundsException e) {

            JOptionPane.showMessageDialog(rootPane, "Digite Um Valor Valido");

        }

    }//GEN-LAST:event_jButtonSubstituirActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed

        comando = jTextFieldComando.getText();
        arduino.send("S00 " + comando + ";");

        

    }//GEN-LAST:event_jButtonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleLedsArduino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleLedsArduino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleLedsArduino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleLedsArduino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleLedsArduino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConcatenar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonSubstituir;
    private javax.swing.JComboBox<String> jComboBoxCustomizacao;
    private javax.swing.JComboBox<String> jComboBoxEfeito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider jSliderAzul;
    private javax.swing.JSlider jSliderBrilho;
    private javax.swing.JSlider jSliderTempo;
    private javax.swing.JSlider jSliderVerde;
    private javax.swing.JSlider jSliderVermelho;
    private javax.swing.JSpinner jSpinnerAzul;
    private javax.swing.JSpinner jSpinnerBrilho;
    private javax.swing.JSpinner jSpinnerTempo;
    private javax.swing.JSpinner jSpinnerVerde;
    private javax.swing.JSpinner jSpinnerVermelho;
    private javax.swing.JTextField jTextFieldComando;
    private javax.swing.JTextField jTextFieldCor;
    // End of variables declaration//GEN-END:variables
}
